**Compute determinant of matrix**

In [9]:
function is_pent_diag(M)
    for (i, row) in enumerate(eachrow(M))
        for (j, col) in enumerate(eachindex(row))
            if(abs(i-j) > 2)
                if(M[i,j] != 0)
                    return false
                end
            end
        end
    end
    return true
end

function det_penta(M)
    if(is_pent_diag(M))
        Pi_4 = M[1,1] #P1 = Pi_4
        Pi_3 = M[2,2]*Pi_4 - M[2,1]*M[1,2] # P2 = Pi_3
        Ri_3 = M[1,2] #R2 = Ri_3 
        Si_3 = M[2,1] #S2 = Si_3
        Pi_2 = M[3,3]*Pi_3 - M[3,2]*M[2,3]*Pi_4 - M[3,1]*M[1,3]*M[2,2] + M[3,1]*M[2,3]*Ri_3 + M[3,2]*M[1,3]*Si_3 #P3 = Pi_2
        Ri_2 = M[2,3]*Pi_4 - M[1,3]*Si_3 #R3 = Ri_2
        Si_2 = M[3,2]*Pi_4 - M[3,1]*Ri_3 #S3 = Si_2
        Pi_1 = M[4,4]*Pi_2 - M[4,3]*M[3,4]*Pi_3 - M[4,2]*M[2,4]*(M[3,3]*Pi_4 - M[3,1]*M[1,3]) + M[4,2]*M[3,4]*Ri_2 + M[4,3]*M[2,4]*Si_2 #P4 = Pi_1
        n = size(M,1)
        Pi = 0
        for i = 5:n
            Ri_1 = M[i-2,i-1]*Pi_3 - M[i-3,i-1]*Si_2
            Si_1 = M[i-1,i-2]*Pi_3 - M[i-1,i-3]*Ri_2
            Pi = M[i,i]*Pi_1 - M[i,i-1]*M[i-1,i]*Pi_2 - 
            M[i,i-2]*M[i-2,i]*(M[i-1,i-1]*Pi_3 - M[i-1,i-3]*M[i-3,i-1]*Pi_4) +
            M[i,i-2]*M[i-1,i]*Ri_1 + M[i,i-1]*M[i-2,i]*Si_1

            Pi_4 = Pi_3
            Pi_3 = Pi_2
            Pi_2 = Pi_1
            Pi_1 = Pi

            Ri_3 = Ri_2
            Ri_2 = Ri_1
            
            Si_3 = Si_2
            Si_2 = Si_1
        end
        return Pi
    else
        print("is not pentadiagonal")
        return 0
    end
end

det_penta (generic function with 1 method)

**Define linear ecuacion to solve and its components**

In [19]:
#Defined as Px=Y
P = [
        [1 2 3 0 0 0];
        [4 5 6 7 0 0];
        [8 9 10 11 12 0];
        [0 12 11 10 9 8];
        [0 0 7 6 5 4];
        [0 0 0 3 2 1];
        ]

Y = [7,5,1,7,9,5]

#Components 
d = [1,5,10,10,5,1]
a = [2,6,11,9,4,0]
b = [3,7,12,8,0,0]
c = [0,4,9,11,6,2]
e = [0,0,8,12,7,3]

6-element Vector{Int64}:
  0
  0
  8
 12
  7
  3

**Function ptrans_1**

In [24]:
function ptrans_1(n, d, a, b, c, e)
    
    #Define arrays
    alpha = zeros(n)
    beta = zeros(n)
    gamma = zeros(n)
    miu = zeros(n)
    zeta = zeros(n)
    X = zeros(n)
    
    #Check determinant
    if det_penta(mat) == 0
        print("No Solutions")
    else 
        #Fill i=1,2
        miu[1] = d[1]
        alpha[1] = a[1]/miu[1]
        beta[1] = b[1]/miu[1]
        zeta[1] = Y[1]/miu[1]
        gamma[2] = c[2]
        miu[2] = d[2] - (alpha[1]*gamma[2])
        alpha[2] = (a[2] - beta[1]*gamma[2])/miu[2]
        beta[2] = b[2]/miu[2]
        zeta[2] = (gamma[2] - zeta[1]*gamma[2])/miu[2]
        #Fill i=3...n-2
        for k in 3:(n-2)
            gamma[k] = c[k] - (alpha[k-2]*e[k])
            miu[k] = d[k] - (beta[k-2]*e[k] - alpha[k-1]*gamma[k])
            alpha[k] = (a[k] - beta[k-1]*gamma[k])/miu[k]
            beta[k] = b[k]/miu[k]
            zeta[k] = (Y[k] - zeta[k-2]*e[k] - zeta[k-1]*gamma[k])/miu[k]
        end
        #Fill i=n-1,n
        gamma[n-1] = c[n-1] - alpha[n-3]*e[n-1]
        miu[n-1] = d[n-1] - beta[n-3]*e[n-1] - alpha[n-2]*gamma[n-1]
        alpha[n-1] = (alpha[n-1] - beta[n-2]*gamma[n-1])/miu[n-1]
        gamma[n] = c[n] - alpha[n-2]*e[n]
        miu[n] = d[n] - beta[n-2]*e[n] - alpha[n-1]*gamma[n]
        zeta[n-1] = (Y[n-1] - zeta[n-1]*e[n-1] - zeta[n-2]*gamma[n-1])/miu[n-1]
        zeta[n] = (Y[n] - zeta[n-1]*e[n] - zeta[n-1]*gamma[n])/miu[n]        
        #Solution Vector X
        X[n] = zeta[n]
        X[n-1] = zeta[n-1] - alpha[n-1]*X[n]
        for i in n-2:-1:1
            X[i] = zeta[i] - alpha[i]*X[i+1] - beta[i]*X[i+2]
        end
    end
    print(X)
end

ptrans_1 (generic function with 1 method)

**Testing function**

In [25]:
ptrans_1(6,d,a,b,c,e)

[-11.557988378268156, 8.998034643665273, 0.18730636364587006, 0.5882774446958625, 0.7818381572607469, -14.130341196820757]